### PR TITLE
Breakpoint race condition fixes

### PR DESCRIPTION
**Pull request by koush**
Update to ES6 to get it to build.
Check in missing package-lock.json.

Fix race conditions around adding and removing breakpoints: 
Breakpoint removal can fail. Assumption that they always succeed may end up with the duk client and server breakpoint indices being out of sync.

Immediately update the breakpoint table upon receiving a response. This will change the duk breakpoint indices for subsequent breakpoint changes, if setBreakPointsRequest was called with multiple breakpoints. Not doing so can, again, cause client and server breakpoint indices to get out of sync.

### CODE REVIEW

**Comment by harold-b** [comment]
Was hoping to have a look at the PR during my upcoming time off, but it looks like it has evolved considerably from a race condition fix :)

Are you taking it upon yourself to update it for current VSCode versions? If so, it is certainly appreciated as I have very little time to look at this, unfortunately.

**Comment by aparajita** [comment]
@koush, awesome! Is this working with the latest Duktape/VS Code?

**Comment by koush** [comment]
Yikes, sorry @harold-b. I kept committing to master, and didn't realize that it would update this pull request as well. I'll break these out.

There's probably two fixes you'd be interested in:
The breakpoint race fix
Improve sourcemap matching behavior.

@aparajita yes, it works with the latest VSCode. I've published my fork here:
https://marketplace.visualstudio.com/items?itemName=koush.duk-debug

**Comment by koush** [comment]
@harold-b I didn't need to do much at all to make it work with the newest VS Code. If I recall, it was simply changing TypeScript to es6 from es5. After that, your extension worked fine with a local build.

**Comment by koush** [comment]
I'm closing this pull request and opening a new one with just the breakpoints fix.

**Comment by aparajita** [comment]
Great work! You might want to either rename your version of the extension or ask @harold-b to withdraw his version, just so there's no confusion for potential users.

**Comment by koush** [comment]
I noted in my version that it was a fork of Harold's. I can rename it as well. Just needed to quickly get this out to a couple people that depend on it. I'd prefer it if Harold took my changes and updated his version. Alternatively, I could publish on his behalf, but that is up to him.

**Comment by aparajita** [comment]
> I noted in my version that it was a fork of Harold's.

I can tell you from long experience that very few will read that note, or even if they do read it, it won't really register.

It doesn't seem that @harold-b has time to maintain the project any more (which is totally understandable, I've been there), so the two best options are:

1. He makes you a collaborator on this repo so you can be a maintainer (better to do that than turn it over to you completely after the recent malicious npm package incident).

2. @harold-b withdraws his version from the VS Code marketplace and you rename your version to something like "Duktape Debugger 2" or "Duktape Debugger++".

**Pull request closed without merging**
