### PR TITLE
Random UI freeze on continue fix

### PR DESCRIPTION
**Pull request by StephenBloomquist**
Change in continueRequest() to match the changes in other debug requests that were made to get around a bug with the UI freezing, solving an issue with the UI freezing when issuing continue requests (hopefully).

### CODE REVIEW

**Comment by harold-b** [comment]
Thanks, I'll have to check this out, because if I recall correctly, I had to leave that one to be triggered on the response because I was getting UI freezing from continue otherwise... I may be remembering wrong, but I do remember having to mess with something because of continue not working properly.

Which version of VS Code are you using?

**Comment by StephenBloomquist** [comment]
I encountered both this and issue #9 in 1.8

When I was stepping through a simple recursive maze-solving program to test the debugger it would randomly freeze after a few recursive continue calls. I put a way to manually send a continue request in your implemented "cmd:" debug function and using that would restore things back to normal. I also couldn't seem to get it to freeze again after doing this.

After a quick scan through your code I found that you made a change to the other request functions that weren't in the continue request. Making a change there (this pull request) fixed the UI freezing for me.

What I _haven't_ tested, now that I think about it, is whether the duplicating breakpoints might have been factoring into it at all.

I've only just begun digging into your code so I apologize if I missed anything obvious.

**Comment by harold-b** [comment]
Oh I don't think you missed anything at all. In fact you went right to the target spot. I'm just asking because I did run into the continue freezing issue before and I do remember I did have to do something hacky to overcome it... And it might be what I mentioned above, I just can't remember :(

I think I'll have some time in the afternoon or tomorrow to test it out and I'll report back what I find. Thanks again.

**Comment by harold-b** [comment]
@StephenBloomquist  did this work well for you? Never ran into the issue again?
I probably won't have time to test it out on my end so I'm thinking of accepting it so that I can close it off so I can have the base ready for implementing a version for duktape 2.0.0

**Comment by StephenBloomquist** [comment]
Yeah whenever I have this change implemented I can't get the UI to freeze on continue, even if I just hold F5 for the entire execution. Whenever I undo the change it happens anywhere from 5 to 10 recursions into my script. Sometimes manually stepping into the next recursive call will let let me get noticeably further with subsequent continues, but it still seems to freeze up after some time. 

Something interesting, though... I've also noticed that having a slow call within the recursive function (such as printing the current state of the maze to the console) seems to prevent the UI from locking when my change isn't implemented.

**Comment by harold-b** [comment]
OK. thanks for the input. I'll merge this so I can grab it before I start refactoring for duktape 2.0.0 support.

Thanks for the extra info as well. These ones are hard to track since it's the VSCode side handling the events for the UI behind the scene. As long as it's not freezing anymore with this change, we should be fine :)

**Pull request merged**
